---
- name: prepare infrastructure
  hosts: build
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Clone a github repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/buildplace/
        clone: yes
        update: yes

    - name: Build application
      command:
        chdir: /tmp/buildplace/
        cmd: mvn package -Dmaven.test.skip -T 1C

    - name: Pull an image
      community.docker.docker_image:
        name: tomcat/9.0.20-jre8-alpine
        source: pull
        load_path: 
          state: load
          path: /tmp/image/

        
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: /tmp/image/
          args:
            volume: /tmp/buildplace/target/hello-1.0.war:/usr/local/tomcat/webapps/hello.war
            listen_port: 8080
        name: b0xmaks/finaltask
        push: yes
        source: build