---
- name: prepare infrastructure && build image && push image to repo
  hosts: build
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      async: 60
      poll: 60

    - name: install a list of packages
      apt:
        pkg:
        - docker.io
        state: present
      async: 60
      poll: 60

    - name: clone a github repository
      git:
        repo: https://github.com/b0xmaks/finaltask.git
        dest: /tmp/buildplace/
        clone: yes
        update: yes
      async: 60
      poll: 60

    - name: build image
      community.docker.docker_image:
        name: finaltask
        build:
          path: /tmp/buildplace/
          args:
            listen_port: 8080
        source: build
      async: 60
      poll: 60

    - name: log into DockerHub
      docker_login:
        username: b0xmaks
        password: pLc2YkxqCx4kENF
      async: 60
      poll: 60

    - name: push to docker hub
      community.docker.docker_image:
        name: finaltask
        repository: b0xmaks/finaltask
        push: yes
        source: local
      async: 60
      poll: 60