---
- name: prepare infrastructure && build image && push image to repo
  hosts: build
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Install a list of packages
      apt:
        pkg:
        - pip
        - git
        - python
        state: present

    - name: install docker
      pip:
        name: docker
        state: present

    - name: clone a github repository
      git:
        repo: https://github.com/b0xmaks/finaltask.git
        dest: /tmp/buildplace/
        clone: yes
        update: yes

    - name: build image
      community.docker.docker_image:
        name: finaltask
        build:
          path: /tmp/buildplace/
          args:
            listen_port: 8080
        source: build

    - name: log into DockerHub
      docker_login:
        username: b0xmaks
        password: pLc2YkxqCx4kENF

    - name: push to docker hub
      community.docker.docker_image:
        name: finaltask
        repository: b0xmaks/finaltask
        push: yes
        source: local