---
- name: prepare infrastructure && build image && push image to repo
  hosts: build
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: install pip
      apt:
        name: pip
        state: present
        update_cache: yes
    
    - name: install docker
      pip:
        name: docker
        state: present

    - name: clone a github repository
      git:
        repo: https://github.com/b0xmaks/finaltask.git
        dest: /tmp/buildplace/
        clone: yes
        update: yes

    - name: build  image
      docker_image:
        path: /tmp/buildplace/
        name: finaltask:latest