---
- name: pull image && start app on stage
  hosts: stage
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
        
    - name: install a list of packages
      apt:
        pkg:
        - docker.io
        - python3-docker
        state: present

    - name: create a data container
      community.docker.docker_container:
        name: go_finaltask
        image: b0xmaks/finaltask:latest
        ports: 8080:8080   
        state: started

