---
- name: pull image && start app on stage
  hosts: stage
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: install pip
      apt:
        name: pip
        state: present
        update_cache: yes
    
    - name: install docker
      pip:
        name: docker
        state: present

    - name: create a data container
      community.docker.docker_container:
        name: go_finaltask
        image: b0xmaks/finaltask:latest
        ports: 8080:8080   
        state: started

